site_name: RedisAI - A Server for Machine and Deep Learning Models
site_url: http://redisai.io
repo_url: https://github.com/RedisAI/RedisAI
repo_name: RedisAI/RedisAI

google_analytics:
  - 'UA-92003007-1'
  - 'auto'

use_directory_urls: true

theme:
  name: 'material'
  language: 'en'
  logo: 'images/logo_small.png'
  favicon: 'images/favicon.png'
  palette:
    primary: 'indigo'
    accent: 'red'
  font:
    text: 'Roboto'
    code: 'Roboto Mono'
  feature:
    tabs: false

extra_javascript:
  - 'https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-MML-AM_CHTML'

nav:
  - 'Home': index.md
  - 'Introduction': intro.md
  - 'Quickstart': quickstart.md
  - 'Commands': commands.md
  - 'Clients': clients.md
  - 'Configuration': configuration.md
  - 'Developer': developer.md
  - 'Performance': performance.md
  - 'Examples': examples.md
  - 'Contributing': contrib.md

markdown_extensions:
  - admonition
  - pymdownx.arithmatex
  - pymdownx.details
  - pymdownx.superfences
  - codehilite:
      guess_lang: False
  - toc:
      permalink: True

plugins:
  - include:
      src_path: docs/snippets
  - versions-menu:
